version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shortify_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortify_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379:6379"
